run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports
    - gosec
    - bodyclose
    - noctx
    - exportloopref

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  gosec:
    excludes:
      - G204 # subprocess launching (needed for tests)

issues:
  exclude-dirs:
    - testdata
